# LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "lis@lis.com",
    "password": "Laura"
}

### ADICIONAR BANDA
@tokenADMIN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NzgzNDA0OSwiZXhwIjoxNjU3ODM3NjQ5fQ.oqWAhKcLTy2YD9eS1jlBK8hAnAUajvPaZ1-Wxm1qMmY
@tokenNORMAL = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTc4MjE4NDUsImV4cCI6MTY1NzgyNTQ0NX0.PfbzhP0JYqfOVxV5i_M9ViO3RSng3TY5b7f6KUGY9eY
POST http://localhost:3003/bands
Content-Type: application/json
authorization: {{tokenADMIN}}

{
    "name": "Turma do Pagode",
    "music_genre": "Pagode",
    "responsible": "Thiaguinho"
}

### ADICIONAR SHOW
POST http://localhost:3003/show
Content-Type: application/json
authorization: {{tokenADMIN}}

{
    "week_day": "Saturday",
    "start_time": 12,
    "end_time":15,
    "band_id": "123"
}