# SIGNUP
POST http://localhost:3003/signup
Content-Type: application/json

{   "name": "Maria",
    "email": "maria@gmail.com",
    "password": "maria123",
    "role": "ADMIN"
}
###


# LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "maria@gmail.com",
    "password": "maria123"
}

### ADICIONAR BANDA

@tokenADMIN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NzgzNDA0OSwiZXhwIjoxNjU3ODM3NjQ5fQ.oqWAhKcLTy2YD9eS1jlBK8hAnAUajvPaZ1-Wxm1qMmY
@tokenNORMAL = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTc4MjE4NDUsImV4cCI6MTY1NzgyNTQ0NX0.PfbzhP0JYqfOVxV5i_M9ViO3RSng3TY5b7f6KUGY9eY

POST http://localhost:3003/bands
Content-Type: application/json
authorization: {{tokenADMIN}}

{
    "name": "Turma do Pagode",
    "music_genre": "Pagode",
    "responsible": "Thiaguinho"
}

### ADICIONAR SHOW
POST http://localhost:3003/show
Content-Type: application/json
authorization: {{tokenAdmin}}

{
    "week_day": "Friday",
    "start_time": 11,
    "end_time":12,
    "band_id": "c4c29442-92b6-4187-823a-60e8fde5720a"
}

### GET BAND DETAILS
GET http://localhost:3003/bands
authorization: {{tokenNORMAL}}
Content-Type: application/json

{
    "name": "my chemical romance"
}
###

@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzNmRkMDhmLTVhMjgtNGIyOC05MjI3LTkwZTEwMzRkM2U1YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1Nzg0ODQ3NCwiZXhwIjoxNjU3ODUyMDc0fQ.9ykZRyU4Ejsqb-oiwIMdKpEwOwUqkb58BVxjYFtkC0A
GET http://localhost:3003/show/Saturday
Authorization: {{tokenAdmin}}